### ISSUE TITLE
Environmental Key

### ISSUE THREAD

**Issue by pulliam** [homework-homies/hw-hub#48]
Hey Phil. 
We are trying to set up a security system where only users that receive our key will be able to sign up. 
I set those keys in the secrets.yml BUT Either I have to push this file to github, or, If I gitgnore it, my collegues can't access any of those keys. How to proceed with that? Looks very confusing and we couldnt figure it out. For now, each of us created a secrets.yml local file in our local repo, but the worry is that, just like happen to us, the users won't be able to access the website even if they have the key. 
Can you please help us?
Thanks

Our secrets.yml file:

```
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b6e4ed8a203733989fc5aa271de00cf667b161fdc0ac3e991fe904cd9142518096ff5f19dce455777dcdea633e275297768167a362b034d32b90aff4654b06
  instructor_key: 2PMgQ6P14sohyBkeO0tkY9V3cnI9d6Z2
  producer_key: Mpf7xR50ZDgoZy9mcnak7qbOy4s60Q6b
  student_key: f3a80YT466052g7b2cz15mu1S2QL78w1
test:
  secret_key_base: 5516b87d87512504239370330207693a7d69222485430755c4de9027924cd9e696dcdce5a6581d3c675a260bdc13c734a5ff1ae1d19910085d90953656c418ea
  instructor_key: 2PMgQ6P14sohyBkeO0tkY9V3cnI9d6Z2
  producer_key: Mpf7xR50ZDgoZy9mcnak7qbOy4s60Q6b
  student_key: f3a80YT466052g7b2cz15mu1S2QL78w1
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  instructor_key: <%= ENV["INSTRUCTOR_KEY"] %>
  producer_key: <%= ENV["PRODUCER_KEY"] %>
  student_key: <%= ENV["STUDENT_KEY"] %>
```

Our .gitignore file:

```
# See https://help.github.com/articles/ignoring-files for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile '~/.gitignore_global'

# Ignore bundler config.
/.bundle

# Ignore all logfiles and tempfiles.
/log/*
!/log/.keep
/tmp
*.yml

/config/secrets.yml
```
